version: "3.8"

services:
  app:
    container_name: app-dev
    stdin_open: true
    image: react-portfolio
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000